"""Sample logs for the Colony page (frontend/colony/samples/): real lab runs exported WITH their hidden read log, plus a synthetic log
shaped like the real incident. Each sample carries the experiment criteria it was run under, read from the run's own record.

AI Village and the real incident are NOT shipped here (research terms / marked "draft, do not share"): export them locally with
`python -m scripts.export_log` and drop the file on the page.

Usage: python -m scripts.make_colony_samples
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path

from backend.analysis import report as R
from scripts.export_log import write_jsonl

ROOT = Path(__file__).resolve().parents[1]
LAB = ROOT / "data" / "lab"
DEST = ROOT / "frontend" / "colony" / "samples"

from experiments.lab.grid import WORLD_WHAT as WORLDS

CONDS ={"none": "links served as written", "inert": "every served link carries a random-looking tag (decoration)",
         "loadbearing": "every served link carries its own session token, which the mirror needs to answer"}
MODELS = {"qwen": "Qwen3-235B", "deepseek": "DeepSeek-V4-Pro"}

SAMPLES = [   # (lab cell, file name, title, what to look for)
    ("W2E-loadbearing-qwen-n30-s4", "lab_early_tip", "Lab: a bad tip from the start (Qwen3-235B)",
     "Every agent adopts the planted tip, through long chains. Click an ant to see what it read and who is downstream."),
    ("W2-inert-qwen-n30-s1", "lab_late_tip_few", "Lab: a late tip that few agents used",
     "The red ants are the outputs that used the bad tip. Click agent-00, the planted tip: everyone downstream of it is the re-check list. Then click agent-01, whose link was fine."),
    ("W4-loadbearing-deepseek-n30-s1", "lab_open_deepseek", "Lab: DeepSeek, the door left open",
     "DeepSeek often fetches its own session instead of using the wiki's link: ants use the same route but not the copy they were served, so most trails are weak or one-of-several. Compare the exact trails with the closed-door run."),
    ("W4G-loadbearing-deepseek-n30-s1", "lab_gated_deepseek", "Lab: DeepSeek, the only door is the coded link",
     "Same model and task, but access only comes through the wiki: every ant has a trail to what it read (compare the trail count with the open-door run)."),
    ("W1-loadbearing-qwen-n30-s1", "lab_no_tip", "Lab: no bad tip, agents just share links",
     "Plain sharing without a planted mistake: some agents copy, some find it alone."),
]


def criteria(cell: str) -> dict:
    s = json.loads((LAB / cell / "run.json").read_text(encoding="utf-8"))
    return {"world": s["world"], "world_what": WORLDS.get(s["world"], ""), "tags": s["cond"], "tags_what": CONDS.get(s["cond"], ""),
            "model": MODELS.get(s["family"], s["family"]), "agents": s["n"], "seed": s["seed"], "max_calls_per_agent": s["max_calls"],
            "truth": "the lab's hidden read log: which copy each agent was served before it used it ('copied' means exposure, not intent)",
            "run": cell}


def main() -> None:
    DEST.mkdir(parents=True, exist_ok=True)
    index = []
    for cell, name, title, look in SAMPLES:
        if not (LAB / cell / "world.json").exists():
            print(f"skip {cell}: not in data/lab")
            continue
        ev = R.events_from_lab(LAB / cell / "world.json", with_reads=True)
        write_jsonl(ev, DEST / f"{name}.jsonl")
        index.append({"file": f"{name}.jsonl", "title": title, "look": look, "reads": True, "criteria": criteria(cell)})
        print(f"  {name:22s} {len(ev):5d} events, {(DEST / (name + '.jsonl')).stat().st_size // 1024} KB")
    inc = ROOT / "frontend" / "card" / "fixtures" / "incident_like.jsonl"
    if inc.exists():
        shutil.copy(inc, DEST / "incident_like.jsonl")
        index.append({"file": "incident_like.jsonl", "title": "Synthetic: a swarm shaped like the real incident", "look": "No read log, like the real incident: many agents type the same vocabulary (declined as coincidence) and the real copies hop between pages.",
                      "reads": False, "criteria": {"world": "synthetic", "world_what": "invented strings only; 60 agents on 40 wiki pages; a few real copies hide in other pages",
                                                    "tags": "none", "tags_what": "no tags", "model": "none (generated by scripts/make_card_fixtures.py)", "agents": 60,
                                                    "truth": "none: like a real investigator, the page can only infer copying from the strings"}})
    (DEST / "index.json").write_text(json.dumps(index, indent=1), encoding="utf-8")
    print(f"-> {DEST} ({len(index)} samples)")


if __name__ == "__main__":
    main()
